// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import CompanyPricesChartController from "./company_prices_chart_controller.js"
application.register("company-prices-chart", CompanyPricesChartController)
